### ISSUE TITLE
chi example don't work because wrong url pattern

### ISSUE THREAD

**Issue by jamesbee** [devopsfaith/krakend-examples#5]
I create a simple demo like `/user/info/{uid}`, it works fine with gin example, but the chi example always return 404 not found, I dig around and found `URIParser.GetEndpointPath` would convert endpoint from `/user/info/{uid}` to `/user/info/:uid`, which adapted by colon style gin router, but failed in brace style router by chi. 

I had to add a convert function after config parsed to change the endpoint url back to brace style and it finally works, any good idea besides this one?

```go
var reg = regexp.MustCompile(`:\w+`)

func convert(cfg config.ServiceConfig) {
	for _, e := range cfg.Endpoints {
		if !strings.Contains(e.Endpoint, ":") {
			continue
		}
		e.Endpoint = reg.ReplaceAllStringFunc(e.Endpoint, func(s string) string {
			return "{" + s[1:] + "}"
		})
	}
}
```

**Comment by kpacha** [comment]
there is a package var for selecting the var style: https://github.com/devopsfaith/krakend-examples/blob/master/gorilla/main.go#L25
